Transform: AWS::Serverless-2016-10-31
Description: SAM app with Typescript and log retention

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
        - x86_64

Parameters:
  GetArticleFunctionName:
    Type: String
    Default: andysibillacom-get-article
  AuthorizerFunctionName:
    Type: String
    Default: andysibillacom-authorizer
  CloudFrontSecretKeyPath:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cloudfront/secret-key
  DomainName:
    Type: String
    Default: api.andysibilla.com
  AcmCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /andysibillacom/acm-certificate-arn

Resources:
  ArticleApi: 
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref AcmCertificateArn
        EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: CloudFrontSecretAuthorizer
        Authorizers:
          CloudFrontSecretAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Headers:
                - X-Origin-Secret
            AuthorizerPayloadFormatVersion: "1.0"
            ResultTtlInSeconds: 300

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref AuthorizerFunctionName
      CodeUri: .
      Handler: authorizer.lambdaHandler
      Environment:
        Variables:
          CLOUDFRONT_SECRET: !Ref CloudFrontSecretKeyPath
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/authorizer.ts

  GetArticle:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref GetArticleFunctionName
      CodeUri: .
      Handler: app.lambdaHandler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/get-article
            Method: get
            RestApiId: !Ref ArticleApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/app.ts

Outputs:
  ApiUrl:
    Value: !Sub "https://${DomainName}/Prod"
  ApiGatewayDomainName:
    Value: !GetAtt ArticleApi.DomainName
  
  