Transform: AWS::Serverless-2016-10-31
Description: SAM app with Typescript and log retention

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
        - x86_64

Parameters:
  FunctionName:
    Type: String
    Default: andysibillacom-get-article

Resources:
  GetArticle:
    Type: AWS::Serverless::Function
    DependsOn: GetArticleLogGroup
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: .
      Handler: app.lambdaHandler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: get-article
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/app.ts

  GetArticleLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/FunctionName"
      RetentionInDays: 1
  